/**
 * App Registry — metadata for all 28 OPOS apps.
 * Components live in ./components.ts (lazy) so the store can depend on this file without cycles.
 */
import {
  Settings,
  Clapperboard,
  MonitorPlay,
  Radio,
  Music2,
  Film,
  Gamepad2,
  Tv,
  CloudSun,
  Sparkles,
  Phone,
  MessageCircle,
  Compass,
  Camera,
  Map,
  CalendarDays,
  Calculator,
  StickyNote,
  Flame,
  FolderOpen,
  SquareTerminal,
  Code2,
  FileText,
  Activity,
  Globe,
  Mail,
  Palette,
  PictureInPicture2,
} from 'lucide-react';
import type { AppCategory, AppDefinition } from '../types';

const TV_UA =
  'Mozilla/5.0 (Linux; Tizen 6.5) AppleWebKit/537.36 (KHTML, like Gecko) 85.0.4183.93/6.5 TV Safari/537.36';

const g = (a: string, b: string, angle = 135) => `linear-gradient(${angle}deg, ${a} 0%, ${b} 100%)`;

export const APPS: AppDefinition[] = [
  /* ------------------------------------------------------------- system */
  {
    id: 'settings',
    name: 'OPOS Settings',
    category: 'system',
    icon: Settings,
    gradient: g('#4b5563', '#111827'),
    accent: '#94a3b8',
    description: 'Network, display, convergence and personalization.',
    launch: 'window',
    kind: 'native',
    defaultSize: { w: 940, h: 640 },
    minSize: { w: 620, h: 420 },
    singleInstance: true,
    tvRow: 'utility',
    keywords: ['preferences', 'wifi', 'display', 'mode'],
  },

  /* ----------------------------------------------------------------- TV */
  {
    id: 'cinema',
    name: 'OPOS Cinema',
    category: 'tv',
    icon: Clapperboard,
    gradient: g('#e50914', '#5b0207'),
    accent: '#e50914',
    description: 'Premium streaming with Widevine DRM verification.',
    launch: 'immersive',
    kind: 'webview',
    url: 'https://bitmovin.com/demos/drm',
    remoteProfile: 'webos',
    defaultSize: { w: 1180, h: 720 },
    singleInstance: true,
    tvRow: 'streaming',
    keywords: ['netflix', 'drm', 'widevine', 'movies'],
  },
  {
    id: 'optube',
    name: 'OPTube',
    category: 'tv',
    icon: MonitorPlay,
    gradient: g('#ff3d3d', '#9b0000'),
    accent: '#ff2a2a',
    description: 'The YouTube TV leanback interface.',
    launch: 'immersive',
    kind: 'webview',
    url: 'https://www.youtube.com/tv',
    userAgent: TV_UA,
    remoteProfile: 'tizen',
    defaultSize: { w: 1180, h: 720 },
    singleInstance: true,
    tvRow: 'streaming',
    keywords: ['youtube', 'video'],
  },
  {
    id: 'opstream',
    name: 'OPStream',
    category: 'tv',
    icon: Radio,
    gradient: g('#a970ff', '#4b1a9e'),
    accent: '#9146ff',
    description: 'Live game streaming from Twitch.',
    launch: 'immersive',
    kind: 'webview',
    url: 'https://www.twitch.tv',
    remoteProfile: 'webos',
    defaultSize: { w: 1180, h: 720 },
    singleInstance: true,
    tvRow: 'streaming',
    keywords: ['twitch', 'live', 'games'],
  },
  {
    id: 'music',
    name: 'OPOS Music',
    category: 'tv',
    icon: Music2,
    gradient: g('#1ed760', '#0b5d2a'),
    accent: '#1ed760',
    description: 'Web Audio synthesized music player with live visualizer.',
    launch: 'immersive',
    kind: 'native',
    defaultSize: { w: 1040, h: 680 },
    singleInstance: true,
    tvRow: 'media',
    keywords: ['spotify', 'audio', 'songs'],
  },
  {
    id: 'plex',
    name: 'Local Plex',
    category: 'tv',
    icon: Film,
    gradient: g('#f9be03', '#a35c00'),
    accent: '#e5a00d',
    description: 'Your local media center library.',
    launch: 'immersive',
    kind: 'native',
    defaultSize: { w: 1120, h: 700 },
    singleInstance: true,
    tvRow: 'media',
    keywords: ['movies', 'library', 'media center'],
  },
  {
    id: 'cloudgamer',
    name: 'Cloud Gamer',
    category: 'tv',
    icon: Gamepad2,
    gradient: g('#22c55e', '#0f3d1e', 160),
    accent: '#3ddc84',
    description: 'Xbox Cloud Gaming & GeForce NOW — controller first.',
    launch: 'immersive',
    kind: 'native',
    defaultSize: { w: 1180, h: 720 },
    singleInstance: true,
    tvRow: 'media',
    keywords: ['xbox', 'geforce', 'games', 'controller'],
  },
  {
    id: 'iptv',
    name: 'Live IPTV',
    category: 'tv',
    icon: Tv,
    gradient: g('#0ea5e9', '#1e3a8a'),
    accent: '#38bdf8',
    description: 'Live channels with an electronic program guide.',
    launch: 'immersive',
    kind: 'native',
    defaultSize: { w: 1180, h: 720 },
    singleInstance: true,
    tvRow: 'live',
    keywords: ['epg', 'channels', 'live tv'],
  },
  {
    id: 'weather',
    name: 'Weather Station',
    category: 'tv',
    icon: CloudSun,
    gradient: g('#38bdf8', '#6366f1'),
    accent: '#7dd3fc',
    description: 'Live forecasts in massive typography.',
    launch: 'immersive',
    kind: 'native',
    defaultSize: { w: 1000, h: 640 },
    singleInstance: true,
    tvRow: 'live',
    keywords: ['forecast', 'temperature'],
  },
  {
    id: 'screensaver',
    name: 'Screensaver',
    category: 'tv',
    icon: Sparkles,
    gradient: g('#0f172a', '#7c3aed'),
    accent: '#a78bfa',
    description: 'Aerial flyovers with an ambient clock.',
    launch: 'overlay',
    kind: 'native',
    singleInstance: true,
    tvRow: 'utility',
    keywords: ['aerial', 'ambient', 'idle'],
  },

  /* ------------------------------------------------------------- Mobile */
  {
    id: 'dialer',
    name: 'Phone',
    category: 'mobile',
    icon: Phone,
    gradient: g('#4ade80', '#15803d'),
    accent: '#22c55e',
    description: 'Dialer with DTMF tones, recents and contacts.',
    launch: 'portrait',
    kind: 'native',
    defaultSize: { w: 380, h: 740 },
    singleInstance: true,
    keywords: ['call', 'dialer'],
  },
  {
    id: 'messages',
    name: 'Messages',
    category: 'mobile',
    icon: MessageCircle,
    gradient: g('#34d399', '#059669'),
    accent: '#10b981',
    description: 'Conversations with chat bubbles.',
    launch: 'portrait',
    kind: 'native',
    defaultSize: { w: 400, h: 740 },
    singleInstance: true,
    keywords: ['sms', 'chat', 'imessage'],
  },
  {
    id: 'mobilebrowser',
    name: 'Browser',
    category: 'mobile',
    icon: Compass,
    gradient: g('#60a5fa', '#1d4ed8'),
    accent: '#3b82f6',
    description: 'A mini browser with a top URL bar.',
    launch: 'portrait',
    kind: 'native',
    defaultSize: { w: 420, h: 760 },
    keywords: ['web', 'safari', 'internet'],
  },
  {
    id: 'camera',
    name: 'Camera',
    category: 'mobile',
    icon: Camera,
    gradient: g('#525252', '#171717'),
    accent: '#d4d4d4',
    description: 'Webcam capture with filters and gallery.',
    launch: 'portrait',
    kind: 'native',
    defaultSize: { w: 420, h: 760 },
    singleInstance: true,
    keywords: ['photo', 'webcam'],
  },
  {
    id: 'maps',
    name: 'Maps',
    category: 'mobile',
    icon: Map,
    gradient: g('#86efac', '#0d9488'),
    accent: '#2dd4bf',
    description: 'OpenStreetMap with place search.',
    launch: 'portrait',
    kind: 'native',
    defaultSize: { w: 420, h: 760 },
    singleInstance: true,
    keywords: ['navigation', 'location', 'osm'],
  },
  {
    id: 'calendar',
    name: 'Calendar',
    category: 'mobile',
    icon: CalendarDays,
    gradient: g('#fb7185', '#e11d48'),
    accent: '#f43f5e',
    description: 'Agenda view with events.',
    launch: 'portrait',
    kind: 'native',
    defaultSize: { w: 400, h: 740 },
    singleInstance: true,
    keywords: ['events', 'schedule', 'agenda'],
  },
  {
    id: 'calculator',
    name: 'Calculator',
    category: 'mobile',
    icon: Calculator,
    gradient: g('#fb923c', '#c2410c'),
    accent: '#f97316',
    description: 'A touch-first calculator.',
    launch: 'portrait',
    kind: 'native',
    defaultSize: { w: 340, h: 560 },
    singleInstance: true,
    keywords: ['math'],
  },
  {
    id: 'notes',
    name: 'Notes',
    category: 'mobile',
    icon: StickyNote,
    gradient: g('#fde047', '#ca8a04'),
    accent: '#facc15',
    description: 'Quick notes with auto-save.',
    launch: 'portrait',
    kind: 'native',
    defaultSize: { w: 420, h: 700 },
    singleInstance: true,
    keywords: ['memo', 'text'],
  },
  {
    id: 'social',
    name: 'Social Feed',
    category: 'mobile',
    icon: Flame,
    gradient: g('#f472b6', '#7c3aed'),
    accent: '#ec4899',
    description: 'An endless vertical reel of creators.',
    launch: 'portrait',
    kind: 'native',
    defaultSize: { w: 400, h: 760 },
    singleInstance: true,
    keywords: ['reels', 'tiktok', 'feed'],
  },

  /* ------------------------------------------------------------ Desktop */
  {
    id: 'files',
    name: 'File Explorer',
    category: 'desktop',
    icon: FolderOpen,
    gradient: g('#fcd34d', '#d97706'),
    accent: '#fbbf24',
    description: 'Browse and manage the OPOS file system.',
    launch: 'window',
    kind: 'native',
    defaultSize: { w: 900, h: 560 },
    minSize: { w: 480, h: 320 },
    keywords: ['finder', 'folders', 'documents'],
  },
  {
    id: 'terminal',
    name: 'Terminal',
    category: 'desktop',
    icon: SquareTerminal,
    gradient: g('#334155', '#020617'),
    accent: '#22d3ee',
    description: 'opsh — the OPOS command line.',
    launch: 'window',
    kind: 'native',
    defaultSize: { w: 760, h: 460 },
    minSize: { w: 420, h: 240 },
    keywords: ['shell', 'cli', 'console', 'bash'],
  },
  {
    id: 'code',
    name: 'Code Editor',
    category: 'desktop',
    icon: Code2,
    gradient: g('#38bdf8', '#1e40af'),
    accent: '#3b82f6',
    description: 'A VS Code-style editor with syntax highlighting.',
    launch: 'window',
    kind: 'native',
    defaultSize: { w: 1080, h: 680 },
    minSize: { w: 600, h: 380 },
    keywords: ['vscode', 'ide', 'programming'],
  },
  {
    id: 'writer',
    name: 'Office Writer',
    category: 'desktop',
    icon: FileText,
    gradient: g('#60a5fa', '#1e3a8a'),
    accent: '#2563eb',
    description: 'Rich text word processor.',
    launch: 'window',
    kind: 'native',
    defaultSize: { w: 940, h: 680 },
    minSize: { w: 560, h: 380 },
    keywords: ['word', 'document', 'docs'],
  },
  {
    id: 'monitor',
    name: 'System Monitor',
    category: 'desktop',
    icon: Activity,
    gradient: g('#34d399', '#0f766e'),
    accent: '#14b8a6',
    description: 'CPU, memory and process telemetry.',
    launch: 'window',
    kind: 'native',
    defaultSize: { w: 900, h: 600 },
    minSize: { w: 560, h: 380 },
    singleInstance: true,
    keywords: ['task manager', 'cpu', 'ram', 'processes'],
  },
  {
    id: 'webbrowser',
    name: 'Web Browser',
    category: 'desktop',
    icon: Globe,
    gradient: g('#818cf8', '#4338ca'),
    accent: '#6366f1',
    description: 'A tabbed desktop-class browser.',
    launch: 'window',
    kind: 'native',
    defaultSize: { w: 1120, h: 720 },
    minSize: { w: 520, h: 360 },
    keywords: ['chrome', 'internet', 'web'],
  },
  {
    id: 'mail',
    name: 'Email',
    category: 'desktop',
    icon: Mail,
    gradient: g('#38bdf8', '#0369a1'),
    accent: '#0ea5e9',
    description: 'Three-pane mail client.',
    launch: 'window',
    kind: 'native',
    defaultSize: { w: 1100, h: 680 },
    minSize: { w: 640, h: 400 },
    singleInstance: true,
    keywords: ['inbox', 'outlook'],
  },
  {
    id: 'photo',
    name: 'Photo Editor',
    category: 'desktop',
    icon: Palette,
    gradient: g('#f0abfc', '#a21caf'),
    accent: '#d946ef',
    description: 'Canvas painting and image filters.',
    launch: 'window',
    kind: 'native',
    defaultSize: { w: 1000, h: 680 },
    minSize: { w: 560, h: 400 },
    keywords: ['paint', 'draw', 'image'],
  },
  {
    id: 'miniplayer',
    name: 'Floating Player',
    category: 'desktop',
    icon: PictureInPicture2,
    gradient: g('#f472b6', '#be123c'),
    accent: '#fb7185',
    description: 'Picture-in-picture mini audio player.',
    launch: 'floating',
    kind: 'native',
    defaultSize: { w: 340, h: 200 },
    singleInstance: true,
    keywords: ['pip', 'mini', 'audio'],
  },
];

export const APP_MAP: Record<string, AppDefinition> = Object.fromEntries(APPS.map((a) => [a.id, a]));

export const getApp = (id: string): AppDefinition | undefined => APP_MAP[id];

export const CATEGORY_LABEL: Record<AppCategory, string> = {
  system: 'System',
  tv: 'TV & Media',
  mobile: 'Mobile',
  desktop: 'Productivity',
};

export const TV_ROWS: { id: NonNullable<AppDefinition['tvRow']>; title: string }[] = [
  { id: 'streaming', title: 'Streaming' },
  { id: 'media', title: 'Music, Movies & Games' },
  { id: 'live', title: 'Live & Info' },
  { id: 'utility', title: 'System' },
];

export function searchApps(query: string): AppDefinition[] {
  const q = query.trim().toLowerCase();
  if (!q) return APPS;
  return APPS.filter(
    (a) =>
      a.name.toLowerCase().includes(q) ||
      a.description.toLowerCase().includes(q) ||
      a.keywords?.some((k) => k.includes(q)),
  );
}
